### ISSUE TITLE
Highlight color incompatible with dark themes

### ISSUE THREAD

**Issue by dchiner** [couzteau/SpellCheck#14]
Please, add a highlight color compatible with dark themes.  The current yellow color makes white text quite invisible. Thank you very much (:

![yellow](https://cloud.githubusercontent.com/assets/5594367/6325262/2d7146b6-bb45-11e4-8294-dedad04569f9.PNG)

**Comment by andrewcio** [comment]
I edited the styles of the plugin `...\Brackets\extensions\user\spell-check\styles.css` so that `span.underline` had a `background-color: rgba(255, 255, 0, 0.5);` 

Works great with the [stripper theme.](https://github.com/visualbam/Brackets-Stripper) Don't know how well it will work for lighter themes, but you could simply find a color that suits your needs and replace the yellow with that.

**Comment by dchiner** [comment]
> I edited the styles of the plugin ...\Brackets\extensions\user\spell-check\styles.css 
> so that span.underline had a background-color: rgba(255, 255, 0, 0.5);

Thanks **andrewcio**, it works fine (:
